export const questions = [
    {
        questionText: 'What is the time complexity of the QuickSort algorithm in the best case?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'O(n)', isCorrect: false },
            { answerText: 'O(n log n)', isCorrect: true },
            { answerText: 'O(n^2)', isCorrect: false },
            { answerText: 'O(log n)', isCorrect: false },
        ],
    },
    {
        questionText: 'Which data structure is used to implement a LIFO (Last-In-First-Out) list?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Queue', isCorrect: false },
            { answerText: 'Stack', isCorrect: true },
            { answerText: 'Linked List', isCorrect: false },
            { answerText: 'Heap', isCorrect: false },
        ],
    },
    {
        questionText: 'What is the size of the integer data type in bytes in a 32-bit system?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: '2', isCorrect: false },
            { answerText: '4', isCorrect: true },
            { answerText: '8', isCorrect: false },
            { answerText: '1', isCorrect: false },
        ],
    },
    {
        questionText: 'Which sorting algorithm has the best average and worst-case time complexity?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Bubble Sort', isCorrect: false },
            { answerText: 'Insertion Sort', isCorrect: false },
            { answerText: 'Merge Sort', isCorrect: true },
            { answerText: 'Selection Sort', isCorrect: false },
        ],
    },
    {
        questionText: 'What is the primary purpose of an index in a database?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'To store large binary data', isCorrect: false },
            { answerText: 'To speed up data retrieval', isCorrect: true },
            { answerText: 'To enforce referential integrity', isCorrect: false },
            { answerText: 'To create data backups', isCorrect: false },
        ],
    },
    {
        questionText: 'Which data structure is used to implement recursion?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Stack', isCorrect: true },
            { answerText: 'Queue', isCorrect: false },
            { answerText: 'Heap', isCorrect: false },
            { answerText: 'Tree', isCorrect: false },
        ],
    },
    {
        questionText: 'Which algorithm is used for finding the shortest path in a weighted graph?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Depth-First Search', isCorrect: false },
            { answerText: 'Breadth-First Search', isCorrect: false },
            { answerText: 'Dijkstra\'s Algorithm', isCorrect: true },
            { answerText: 'Prim\'s Algorithm', isCorrect: false },
        ],
    },
    {
        questionText: 'Which sorting algorithm has the best time complexity for small datasets?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Merge Sort', isCorrect: false },
            { answerText: 'QuickSort', isCorrect: false },
            { answerText: 'Insertion Sort', isCorrect: true },
            { answerText: 'Bubble Sort', isCorrect: false },
        ],
    },
    {
        questionText: 'What does the acronym SQL stand for?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Simple Query Language', isCorrect: false },
            { answerText: 'Structured Query Language', isCorrect: true },
            { answerText: 'Standard Query Language', isCorrect: false },
            { answerText: 'System Query Language', isCorrect: false },
        ],
    },
    {
        questionText: 'In which data structure is the traversal order based on a LIFO approach?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Queue', isCorrect: false },
            { answerText: 'Heap', isCorrect: false },
            { answerText: 'Stack', isCorrect: true },
            { answerText: 'Tree', isCorrect: false },
        ],
    },
    {
        questionText: 'What is the time complexity of the binary search algorithm?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'O(n)', isCorrect: false },
            { answerText: 'O(log n)', isCorrect: true },
            { answerText: 'O(n log n)', isCorrect: false },
            { answerText: 'O(1)', isCorrect: false },
        ],
    },
    {
        questionText: 'Which type of memory is typically the smallest and fastest in a computer?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Cache Memory', isCorrect: true },
            { answerText: 'RAM', isCorrect: false },
            { answerText: 'Hard Disk', isCorrect: false },
            { answerText: 'Optical Disk', isCorrect: false },
        ],
    },
    {
        questionText: 'Which algorithm is used to find the strongly connected components in a directed graph?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Prim\'s Algorithm', isCorrect: false },
            { answerText: 'Kruskal\'s Algorithm', isCorrect: false },
            { answerText: 'Dijkstra\'s Algorithm', isCorrect: false },
            { answerText: 'Tarjan\'s Algorithm', isCorrect: true },
        ],
    },
    {
        questionText: 'Which type of algorithm makes use of a "greedy" strategy?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Depth-First Search', isCorrect: false },
            { answerText: 'Dynamic Programming', isCorrect: false },
            { answerText: 'Breadth-First Search', isCorrect: false },
            { answerText: 'Greedy Algorithm', isCorrect: true },
        ],
    },
    {
        questionText: 'Which type of addressing mode involves adding an immediate value to the contents of a register?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Indirect Addressing', isCorrect: false },
            { answerText: 'Indexed Addressing', isCorrect: false },
            { answerText: 'Immediate Addressing', isCorrect: true },
            { answerText: 'Register Addressing', isCorrect: false },
        ],
    },
    {
        questionText: 'In the context of computer networks, what does the acronym LAN stand for?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Long Area Network', isCorrect: false },
            { answerText: 'Local Area Network', isCorrect: true },
            { answerText: 'Large Array Network', isCorrect: false },
            { answerText: 'Low-level Access Network', isCorrect: false },
        ],
    },
    {
        questionText: 'Which data structure is used to implement a symbol table?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Heap', isCorrect: false },
            { answerText: 'Stack', isCorrect: false },
            { answerText: 'Hash Table', isCorrect: true },
            { answerText: 'Queue', isCorrect: false },
        ],
    },
    {
        questionText: 'Which algorithm is used to find the minimum spanning tree of a connected, undirected graph?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Breadth-First Search', isCorrect: false },
            { answerText: 'Depth-First Search', isCorrect: false },
            { answerText: 'Kruskal\'s Algorithm', isCorrect: true },
            { answerText: 'Dijkstra\'s Algorithm', isCorrect: false },
        ],
    },
    {
        questionText: 'Which type of storage device uses a laser to read and write data?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Hard Disk Drive', isCorrect: false },
            { answerText: 'Solid State Drive', isCorrect: false },
            { answerText: 'Optical Disk Drive', isCorrect: true },
            { answerText: 'Flash Drive', isCorrect: false },
        ],
    },
    {
        questionText: 'What is the time complexity of the BFS algorithm on an undirected graph with V vertices and E edges?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'O(V + E)', isCorrect: true },
            { answerText: 'O(V log E)', isCorrect: false },
            { answerText: 'O(E log V)', isCorrect: false },
            { answerText: 'O(E + V^2)', isCorrect: false },
        ],
    },
    {
        questionText: 'Which logic gate produces the complement of its input?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'AND Gate', isCorrect: false },
            { answerText: 'OR Gate', isCorrect: false },
            { answerText: 'NOT Gate', isCorrect: true },
            { answerText: 'XOR Gate', isCorrect: false },
        ],
    },
    {
        questionText: 'In the context of operating systems, what does the term "thrashing" refer to?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Excessive CPU utilization', isCorrect: false },
            { answerText: 'Excessive I/O operations', isCorrect: false },
            { answerText: 'Excessive context switching', isCorrect: false },
            { answerText: 'Excessive paging', isCorrect: true },
        ],
    },
    {
        questionText: 'Which algorithm is used for finding the longest common subsequence of two sequences?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'KMP Algorithm', isCorrect: false },
            { answerText: 'Bellman-Ford Algorithm', isCorrect: false },
            { answerText: 'Longest Path Algorithm', isCorrect: false },
            { answerText: 'Dynamic Programming', isCorrect: true },
        ],
    },
    {
        questionText: 'What does the term "mutex" stand for in computer science?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Mutually Exclusive', isCorrect: true },
            { answerText: 'Multi-Threaded Execution', isCorrect: false },
            { answerText: 'Mutex Operator', isCorrect: false },
            { answerText: 'Multicast Exchange', isCorrect: false },
        ],
    },
    {
        questionText: 'Which programming paradigm is based on "objects" that can contain data and code to manipulate the data?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Imperative', isCorrect: false },
            { answerText: 'Functional', isCorrect: false },
            { answerText: 'Procedural', isCorrect: false },
            { answerText: 'Object-Oriented', isCorrect: true },
        ],
    },
    {
        questionText: 'Which algorithm is used for finding the shortest path in a weighted graph with negative edges?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Floyd-Warshall Algorithm', isCorrect: true },
            { answerText: 'Dijkstra\'s Algorithm', isCorrect: false },
            { answerText: 'Prim\'s Algorithm', isCorrect: false },
            { answerText: 'Kruskal\'s Algorithm', isCorrect: false },
        ],
    },
    {
        questionText: 'What is the primary advantage of using dynamic programming?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'Minimal memory usage', isCorrect: false },
            { answerText: 'Faster execution on all inputs', isCorrect: false },
            { answerText: 'Ease of implementation', isCorrect: false },
            { answerText: 'Optimized solution for subproblems', isCorrect: true },
        ],
    },
    {
        questionText: 'Which protocol is used to retrieve emails from a remote server to a local client?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'SMTP', isCorrect: false },
            { answerText: 'HTTP', isCorrect: false },
            { answerText: 'POP3', isCorrect: true },
            { answerText: 'FTP', isCorrect: false },
        ],
    },
    {
        questionText: 'Which sorting algorithm is known for its adaptive nature?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'QuickSort', isCorrect: false },
            { answerText: 'Bubble Sort', isCorrect: false },
            { answerText: 'Insertion Sort', isCorrect: true },
            { answerText: 'Merge Sort', isCorrect: false },
        ],
    },
    {
        questionText: 'In the context of database normalization, which normal form ensures that there are no partial dependencies?',
        points: '+1',
        Negative: '-0.33',
        answerOptions: [
            { answerText: 'First Normal Form', isCorrect: false },
            { answerText: 'Second Normal Form', isCorrect: false },
            { answerText: 'Third Normal Form', isCorrect: true },
            { answerText: 'Fourth Normal Form', isCorrect: false },
        ],
    },
];

